Praktek BOW
=============================

***Alfin Rifaldi (A11.2022.14684)***

In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset = pd.read_csv('Restaurant_Reviews.tsv', delimiter='\t')

In [3]:
dataset.shape

(1000, 2)

In [4]:
dataset.head(10)

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1
5     Now I am getting angry and I want my damn pho.      0
6              Honeslty it didn't taste THAT fresh.)      0
7  The potatoes were like rubber and you could te...      0
8                          The fries were great too.      1
9                                     A great touch.      1

In [5]:
#mengubah tipe data pada kolom Review menjadi string
dataset_feature = dataset['Review'].astype(str)

In [6]:
dataset_label = dataset['Liked']

In [7]:
dataset_feature

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object

In [8]:
dataset_label

0      1
1      0
2      0
3      1
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: Liked, Length: 1000, dtype: int64

# Cek distribusi label

In [11]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [ ]:
# Visualizing the target variable
plt.figure(figsize=(12,8))
sns.distplot(dataset_label, label=f'target, skew: {dataset_label.skew():.2f}')
plt.legend(loc='best')
plt.show()

In [10]:
dataset_label.value_counts()

Liked
1    500
0    500
Name: count, dtype: int64

# BOW

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

In [15]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(dataset_feature)

In [16]:
feature_names = vectorizer.get_feature_names_out()
print(", ".join(feature_names))

00, 10, 100, 11, 12, 15, 17, 1979, 20, 2007, 23, 30, 30s, 35, 40, 40min, 45, 4ths, 5lb, 70, 85, 90, 99, about, above, absolute, absolutely, absolutley, accident, accommodations, accomodate, accordingly, accountant, ache, acknowledged, across, actual, actually, added, affordable, after, afternoon, again, ago, ahead, airline, airport, ala, albondigas, all, allergy, almonds, almost, alone, also, although, always, am, amazing, ambiance, ambience, amount, ample, an, and, andddd, angry, annoying, another, anticipated, any, anymore, anyone, anything, anytime, anyway, anyways, apart, apologize, apology, app, appalling, apparently, appealing, appetite, appetizer, appetizers, apple, approval, are, area, aren, arepas, aria, around, array, arrived, arrives, arriving, article, as, ask, asked, asking, assure, at, ate, atmosphere, atrocious, attached, attack, attention, attentive, attitudes, auju, authentic, average, avocado, avoid, avoided, away, awesome, awful, awkward, awkwardly, ayce, az, baba, b

In [17]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [19]:
X2 = vectorizer2.fit_transform(dataset_feature)

In [20]:
feature_names2 = vectorizer2.get_feature_names_out()
print(", ".join(feature_names2))

10 minutes, 10 times, 100 recommended, 100 times, 11 99, 12 ridiculous, 15 minutes, 17 burger, 1979 and, 20 minutes, 20 you, 2007 and, 23 which, 30 min, 30 minutes, 30s and, 35 big, 35 minutes, 40 and, 40 bucks, 40 minutes, 40min passed, 45 minutes, 4ths gristle, 5lb piece, 70 when, 85 for, 90 has, 99 for, about 10, about 20, about great, about half, about here, about on, about our, about taste, about the, about this, about two, about was, about working, above and, above average, absolute must, absolutely amazing, absolutely be, absolutely delicious, absolutely flat, absolutely no, absolutely stars, absolutley fantastic, accident and, accommodations for, accomodate for, accountant to, ache and, acknowledged then, actual experience, actually rare, added extra, added gratuity, affordable prices, after 10, after 20, after all, after going, after one, after pulled, after some, after the, after this, after two, after us, after waiting, again because, again if, again will, ago and, ahead of,

In [21]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Simulasi Corpus

In [22]:
corpus = [
    'The atmosphere was cozy and inviting'
    'The menu offered a delightful variety of dishes'
    'The staff were attentive and friendly'
    'The prices were slightly on the higher side'
    'The presentation of each dish was impeccable'
    'Dining at [Restaurant Name] was a memorable experience'
]

In [23]:
vectorizer = CountVectorizer()

In [24]:
Z = vectorizer.fit_transform(corpus)

In [25]:
vectorizer.get_feature_names_out()

array(['and', 'at', 'atmosphere', 'attentive', 'cozy', 'delightful',
       'dish', 'dishesthe', 'each', 'experience', 'friendlythe', 'higher',
       'impeccabledining', 'invitingthe', 'memorable', 'menu', 'name',
       'of', 'offered', 'on', 'presentation', 'prices', 'restaurant',
       'sidethe', 'slightly', 'staff', 'the', 'variety', 'was', 'were'],
      dtype=object)

In [26]:
print(Z.toarray())

[[2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 2 1 3 2]]


In [27]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))

In [28]:
Z2 = vectorizer2.fit_transform(corpus)

In [29]:
vectorizer2.get_feature_names_out()

array(['and friendlythe', 'and invitingthe', 'at restaurant',
       'atmosphere was', 'attentive and', 'cozy and',
       'delightful variety', 'dish was', 'dishesthe staff', 'each dish',
       'friendlythe prices', 'higher sidethe', 'impeccabledining at',
       'invitingthe menu', 'memorable experience', 'menu offered',
       'name was', 'of dishesthe', 'of each', 'offered delightful',
       'on the', 'presentation of', 'prices were', 'restaurant name',
       'sidethe presentation', 'slightly on', 'staff were',
       'the atmosphere', 'the higher', 'variety of', 'was cozy',
       'was impeccabledining', 'was memorable', 'were attentive',
       'were slightly'], dtype=object)

In [30]:
print(Z2.toarray())

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]
